version: "2"

services:

    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_TAG}
        mem_limit: 4g
        depends_on: 
            - postgres  
        environment:
            JAVA_TOOL_OPTIONS: >-
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
            JAVA_OPTS : >-
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.driver=org.postgresql.Driver
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco  
                -Dalfresco_user_store.adminpassword=209c6174da490caeb422f3fa5a7ae634
                -Dsystem.preferred.password.encoding=bcrypt10
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.port.ssl=8983
                -Dsolr.secureComms=secret
                -Dsolr.baseUrl=/solr
                -Dindex.subsystem.name=solr6
                -Dsolr.sharedSecret=7ru0xcy0nqb  
                -Dalfresco.host=${SERVER_NAME}
                -Dalfresco.port=8080
                -Dapi-explorer.url=http://${SERVER_NAME}:8080/api-explorer
                -Dalfresco.protocol=http 
                -Dshare.host=${SERVER_NAME}
                -Dshare.port=8080
                -Dshare.protocol=http 
                -Daos.baseUrlOverwrite=http://${SERVER_NAME}/alfresco/aos 
                -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false 
                -Dopencmis.server.override=true
                -Dopencmis.server.value=http://${SERVER_NAME}:8080
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/ 
                -Dhttpclient.config.transform.connectionRequestTimeout=500000
                -Dcsrf.filter.enabled=false
                -Dalfresco.restApi.basicAuthScheme=true
                -Dauthentication.protection.enabled=false
                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Dgoogledocs.enabled=false   
                -Ddev.email.not.sent=true  
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
        volumes: 
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data
        

    transform-core-aio:
        image: quay.io/alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
        restart: on-failure  
        mem_limit: 2g
        environment:
            JAVA_OPTS: >-
              -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
              -Dserver.tomcat.threads.max=12
              -Dserver.tomcat.threads.min=4
              -Dlogging.level.org.alfresco.transform.common.TransformerDebug=ERROR

    share:
        image: quay.io/alfresco/alfresco-share:${SHARE_TAG}
        mem_limit: 1g
        environment:
          REPO_HOST: "alfresco"
          REPO_PORT: "8080"
          JAVA_OPTS: >-
            -XX:MinRAMPercentage=50
            -XX:MaxRAMPercentage=80
            -Dalfresco.host=localhost
            -Dalfresco.port=8080
            -Dalfresco.context=alfresco
            -Dalfresco.protocol=http

    digital-workspace:
      image: quay.io/alfresco/alfresco-digital-workspace:${ADW_TAG}
      mem_limit: 128m
      environment:
        APP_CONFIG_PROVIDER: "ECM"
        APP_CONFIG_AUTH_TYPE: "BASIC"
        BASE_PATH: ./
        APP_BASE_SHARE_URL: "http://localhost:8080/workspace/#/preview/s"        
    
    postgres:
        image: docker.io/postgres:${POSTGRES_TAG}
        mem_limit: 1g
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: >-
            postgres
              -c max_connections=200
              -c logging_collector=on
              -c log_min_messages=LOG
              -c log_directory=/var/log/postgresql
        ports:
            - 5432:5432
        volumes: 
            - ./data/postgres-data:/var/lib/postgresql/data

    solr6:
        image: docker.io/alfresco/alfresco-search-services:2.0.8.2
        mem_limit: 2g
        environment:
          SOLR_ALFRESCO_HOST: "alfresco"
          SOLR_ALFRESCO_PORT: "8080"
          SOLR_SOLR_HOST: "solr6"
          SOLR_SOLR_PORT: "8983"
          SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco"
          ALFRESCO_SECURE_COMMS: "secret"
          JAVA_TOOL_OPTIONS: >-
            -Dalfresco.secureComms.secret=7ru0xcy0nqb
          SOLR_OPTS: >-
            -XX:-UseLargePages
            -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
            -Dalfresco.secureComms.secret=7ru0xcy0nqb 
        volumes: 
            - ./data/solr-data:/opt/alfresco-search-services/data   

    activemq:
        image: docker.io/alfresco/alfresco-activemq:${ACTIVEMQ_TAG}
        ports:
          - "8161:8161"
        volumes:
          - ./data/activemq-data:/opt/activemq/data  

    proxy:
        image: docker.io/alfresco/alfresco-acs-nginx:${ACS_NGINX_TAG}
        depends_on:
          - alfresco  
        environment:  
          - DISABLE_SYNCSERVICE=true   
          - DISABLE_CONTROL_CENTER=true  
          - USE_SSL=false
        ports:
          - "8080:8080"
        links:  
          - alfresco 
          - share